.TH WMPUS 1 "October 2011" wmpus
.SH NAME
wmpus \- cross platform window manager
.SH SYNOPSIS
.B wmpus
.SH DESCRIPTION
wmpus is portable window manager. Currently it supports wmii like window
management and includes x11 and win32 backends.
.SH OPTIONS
.TP
There are no options
.SH WMII WINDOW MANAGEMENT
The wmii window management mode mimics the behavior of the \fBwmii\fR(1) window
manager. By default, the \fBalt\-\fR prefix is used for most window management
commands and is used along with the h, j, k, and l keys to focused different
windows.
.P
The \fBalt\-shift\-\fR prefix is used for moving windows and works similar to
changing the focus. The mouse is used for resizing windows and also for
changing focus.
.SS Changing focus
.TP
.B Alt\-j
Focus window \fIbelow\fR the currently focused window
.TP
.B Alt\-k
Focus window \fIabove\fR the currently focused window
.TP
.B Alt\-h
Focus column to the \fIleft\fR of the currently focused column
.TP
.B Alt\-l
Focus column to the \fIright\fR of the currently focused column
.SS Moving windows around
.TP
.B Alt\-Shift\-j
Move the currently focused window \fIdown\fR
.TP
.B Alt\-Shift\-k
Move the currently focused window \fIup\fR
.TP
.B Alt\-Shift\-h
Move the currently focused window to the \fIleft\fR
.TP
.B Alt\-Shift\-l
Move the currently focused window to the \fIright\fR
.SS Column modes
.TP
.B Alt\-d
Switch the current column to \fIsplit\fR mode
.TP
.B Alt\-s
Switch the current to \fIstack\fR mode
.TP
.B Alt\-m
Switch the current to \fImaximized\fR mode
.SS Tag commands
.TP
.B Alt\-[0..n]
Switch to tag n
.TP
.B Alt\-Shift\-[0..n]
Move the currently focused window to tag n
.SS Mouse commands
.TP
.B Pointer
Moving the mouse over a window focuses that window.
.TP
.B Alt-Button3
Click and drag resizes the window under the cursor.
.SH X11 BACKEND
The X11 backend draws a small 2px border around each window. The border for the
currently focused window is set to a lighter color than the rest.
.SH WIN32 BACKEND
The Win32 backend uses the existing window borders and title bars. It also
leaves a narrow space between the windows so that they look more natural in a
Windows environment.
.SH CUSTOMIZATION
The backend and window management modes can be changed by linking in the
correct object file.
.P
Some settings can be changed at compiling time using the C Preprocessor's -D
directive.
.TP
\fBBORDER\fR=\fIN\fR
Set the border width for wm-x11 to N pixels. Default 2
.TP
\fBMODKEY\fR=\fIkey\fR
Modifier used for window management commands, can be either \fIalt\fR,
\fIctrl\fR, \fIshift\fR, or \fIwin\fR. Default alt
.TP
\fBMARGIN\fR=\fIN\fR
Margin in pixels between windows for wm-wmii. X11 default 0, Win32 default 15
.TP
\fBSTACK\fR=\fIN\fR
Height in pixels for non-focused windows when the column is set to stack mode.
.SH SEE ALSO
.BR wmii (1),
.BR dwm (1),
.BR dzen (1)
.SH BUGS
Many
